### ISSUE TITLE
ResNet finetuning

### ISSUE THREAD

**Issue by alkamid** [revilokeb/wide_residual_nets_caffe#2]
Hi @revilokeb, I'm sorry for crashing into your github project, but I can't find another way to contact you. On DeepDetect repo, you suggested you got ResNet-50 to work on less than 4GB memory for finetuning. Could you please have a look at my efforts and suggest what I may be doing wrong: https://github.com/beniz/deepdetect/issues/156?. Feel free to drop me an e-mail, reply in that issue or anywhere you feel relevant.

**Comment by revilokeb** [comment]
@alkamid sorry for coming to this so belatedly. Is this still of concern to you?

**Comment by revilokeb** [comment]
@alkamid the general approach is to take the maximum batch_size that is still working on your GPU (probably something like ~4 with ResNet 50 on AWS 4GB I would guess) and then set iter_size in your solver.prototxt to 8 or 16 (-> effective batch_size then is 32 / 64)

**Comment by alkamid** [comment]
@revilokeb thanks for the reply. I didn't know about `iter_size`, but I tried setting it to 8 (and even 4) just now. Unfortunately, I'm still running out of memory. Strangely enough, it always crashes on #47:

```
I0921 21:02:43.831758  1637 solver.cpp:404]     Test net output #47: probt = 0.423409
F0921 21:02:43.888599  1637 syncedmem.cpp:56] Check failed: error == cudaSuccess (2 vs. 0)  out of memory
```

Do you happen to have the .prototxt files that you used to train resnets? Would you be able to share them?

**Comment by revilokeb** [comment]
@alkamid unfortunately I don't have that .prototxt anymore but there was not a lot of magic if I remember correctly. I could check on one of my GPUs whats the memory footprint of ResNet50 (watch nvidia-smi) if that helps.

Be carefull to not only reduce batch_size for training but also for testing as this adds up. From your snippet it looks as if you are running out of mem at test time. You might reduce your test batch_size even to 1 - I would be very surprised if you were not able to train a ResNet 50 then with training batch_size ~ 4 on 4GB (reducing test batch_size to 1 of course makes testing take longer...)

**Comment by alkamid** [comment]
@revilokeb I followed your advice but the problem persisted. However, now Amazon provides 12GB GPUs on AWS, so I'm not that inclined on finding the issue. Thanks for your time and help!
